project_name: xt

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
  - binary: bin/xt
    main: ./cmd
    ldflags:
      - -s -w -X github.com/adamkobi/xt/internal/build.Version={{.Version}} -X github.com/adamkobi/xtinternal/build.Date={{time "2006-01-02"}}
      - -X main.updaterEnabled=adamkobi/xt
    id: macos
    goos: [darwin]
    goarch: [amd64]
  - binary: bin/xt
    main: ./cmd
    ldflags:
      - -s -w -X github.com/adamkobi/xt/internal/build.Version={{.Version}} -X github.com/adamkobi/xtinternal/build.Date={{time "2006-01-02"}}
      - -X main.updaterEnabled=adamkobi/xt
    id: linux
    goos: [linux]
    goarch: [amd64]

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz