project_name: xt

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: bin/xt
      main: ./cmd/xt
      ldflags:
        - -s -w -X github.com/adamkobi/xt/command.Version={{.Version}} -X github.com/adamkobi/xt/command.BuildDate={{time "2006-01-02"}}
        - -X main.updaterEnabled=adamkobi/xt
    id: macos
    goos: [darwin]
    goarch: [amd64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz